#!/usr/bin/python3

#
# Make a table of Ensoniq frequency values (high and low bytes)
# Corresponding to the frequency values used in BBC Micro
# SOUND statements.
#

base=123.47 / 16.0 * 1.573 * 440.0 / 739.99

print("\nEFREQHIGH");
for i in range(0,256):
  v = 2**(i/48)*base
  print("          DB >{:.0f}".format(v * 10))

print("\nEFREQLOW");
for i in range(0,256):
  v = 2**(i/48)*base
  print("          DB <{:.0f}".format(v * 10))
