#!/bin/sh
for file in APPLECORN AUXMEM.BYTWRD AUXMEM.CHARIO AUXMEM.HOSTFS AUXMEM.INIT AUXMEM.KERNEL AUXMEM.MISC AUXMEM.MOSEQU AUXMEM.VDU LOADER MAINMEM; do
  cadius extractfile applecorn.po /APPLECORN/${file}.S .
  rm _FileInformation.txt
  cadius clearhighbit ${file}.S\#040000
  cadius indentfile ${file}.S\#040000
done
