#!/bin/sh
for file in APPLECORN LOADER MAINMEM AUXMEM; do
  cadius extractfile applecorn.po /APPLECORN/${file}.S .
  rm _FileInformation.txt
  cadius clearhighbit ${file}.S\#040000
  cadius indentfile ${file}.S\#040000
done
