#!/bin/sh

FILENAME=Clinton_Turner_V2_Version2.ROM
dd if=$FILENAME of=1 bs=256 count=1 skip=0
dd if=$FILENAME of=2 bs=256 count=1 skip=1
dd if=$FILENAME of=3 bs=256 count=1 skip=2
dd if=$FILENAME of=4 bs=256 count=1 skip=3
dd if=$FILENAME of=5 bs=256 count=1 skip=4
dd if=$FILENAME of=6 bs=256 count=1 skip=5
dd if=$FILENAME of=7 bs=256 count=1 skip=6
dd if=$FILENAME of=8 bs=256 count=1 skip=7
dd if=/dev/zero of=z bs=256 count=1
cat z 2 1 4 z 6 5 8 > font.dat#06A900
rm 1 2 3 4 5 6 7 8 z

